Joao/read ipc
elixir-nx/explorer pull request #144
Opened 2022-03-30 02:22 UTC by kimjoaoun

If approved, this Pull Requests closes #140.

This PR creates:

```
Explorer.DataFrame.read_ipc/1
Explorer.DataFrame.write_ipc/2
```

"Example":

```Elixir

# First we create an IPC file.

Explorer.Datasets.iris
|> Explorer.DataFrame.write_ipc("iris_test.ipc")

# Then we read the same IPC file into Elixir.

Explorer.DataFrame.read_ipc("iris_test.ipc")

```

2022-03-30 02:32 UTC, kimjoaoun commented
@cigrainger sorry for not asking permission to do this PR 😬

2022-03-30 04:04 UTC, cigrainger requested changes
Just a couple minor changes needed. Thanks for this one!

2022-03-30 04:04 UTC, cigrainger commented on lib/explorer/data_frame.ex
> +  def read_ipc(filename), do: Explorer.PolarsBackend.DataFrame.read_ipc(filename)
Check out the other `read_` functions for setting the default backend.

2022-03-30 04:04 UTC, cigrainger commented on lib/explorer/polars_backend/data_frame.ex
> +  end
These will need `@impl true`.

2022-03-31 00:18 UTC, merged

2022-03-31 06:53 UTC, josevalim commented
So if I get this right, is this mostly a way to serialize/deserialize dataframes? What are the use cases? Maybe we should have one or two paragraphs in the docs breaking this a bit down? :)

2022-03-31 22:39 UTC, cigrainger commented
That's exactly right @josevalim. https://arrow.apache.org/docs/format/Columnar.html#serialization-and-interprocess-communication-ipc

I think it's particularly useful with [feather](https://arrow.apache.org/docs/python/feather.html) which is used with R and Python quite a bit.

2022-03-31 23:49 UTC, kimjoaoun commented
I've just realised that `read_ipc` and `write_ipc` might have some extra arguments, like ["with_compression", on write_ipc](https://pola-rs.github.io/polars/polars_io/ipc/struct.IpcWriter.html). Can I implement them on a new PR?

2022-03-31 23:50 UTC, cigrainger commented
@kimjoaoun Yes please! And could you throw in a bit of explanation to handle #147?

2022-03-31 23:51 UTC, kimjoaoun commented
Of course!